version: "3"
services:
  client:
    image: node:12-alpine
    working_dir: /client
    volumes:
      - ./client:/client:cached
    command: npm start
    environment:
      NODE_ENV: development
      BABEL_DISABLE_CACHE: 1
    ports:
      - 3000:3000
    expose:
      - 3000
