version: 2

jobs:
  test:
    docker:
      - image: circleci/node:13
    working_directory: ~/repo
    steps:
      - checkout
      - run: npm run install-all && npm t

  deploy:
    docker:
      - image: circleci/node:13
    working_directory: ~/repo
    steps:
      - checkout
      - deploy:
          command: >
            ssh -o "StrictHostKeyChecking no" root@188.166.76.76
            "cd /root/marxist.space && \
               git fetch && \
               git reset --hard origin/master && \
               npm run install-all && \
               npm run build && \
               cd server && \
               ./node_modules/.bin/forever restart 0 && \
               sleep 2 && \
               ./node_modules/.bin/forever logs 0"

workflows:
  version: 2
  test:
    jobs:
      - test
  deploy:
    jobs:
      - deploy:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
