version: 2

jobs:
  test:
    docker:
      - image: circleci/node:14
    working_directory: ~/repo
    steps:
      - checkout
      - run: npm ci && npm t
      - run: bash <(curl -s https://codecov.io/bash)

workflows:
  version: 2
  test:
    jobs:
      - test
